package com.ssafy.eggmoney.stock.entity;

public enum StockItem {
    KOSPI, KOSDAQ, AUTOMOTIVE, SEMICONDUCTOR, HEALTHCARE, BANKING, ENERGY_CHEMICAL,
    STEEL, CONSTRUCTION, TRANSPORTATION, MEDIA_ENTERTAINMENT, IT, UTILITIES
}
