version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - back
    image: ribbon03/frontend


  backend:
    build:
      context: ./backend
    ports:
      - "8081:8080"
    image: ribbon03/backend